const signMetadata = [
  {
    identifier: "r1",
    primary_category: "regulatory_signs",
    secondary_category: "control_signs",
    description: "stop sign",
  },
  {
    identifier: "r1_2",
    primary_category: "regulatory_signs",
    secondary_category: "control_signs",
    description: "stop/yield sign",
  },
  {
    identifier: "r1_4",
    primary_category: "regulatory_signs",
    secondary_category: "control_signs",
    description: "4 way stop sign",
  },
  {
    identifier: "r1_5",
    primary_category: "regulatory_signs",
    secondary_category: "control_signs",
    description: "stop/ry-go sign",
  },
  {
    identifier: "r2",
    primary_category: "regulatory_signs",
    secondary_category: "control_signs",
    description: "yield sign",
  },
  {
    identifier: "r2_1",
    primary_category: "regulatory_signs",
    secondary_category: "control_signs",
    description: "yield to pedestrians sign",
  },
  {
    identifier: "r2_2",
    primary_category: "regulatory_signs",
    secondary_category: "control_signs",
    description: "yield to traffic cycle sign",
  },
  {
    identifier: "r3",
    primary_category: "regulatory_signs",
    secondary_category: "control_signs",
    description: "no entry sign",
  },
  {
    identifier: "r4_1",
    primary_category: "regulatory_signs",
    secondary_category: "control_signs",
    description: "one-way roadway sign: left",
  },
  {
    identifier: "r4_2",
    primary_category: "regulatory_signs",
    secondary_category: "control_signs",
    description: "one-way roadway sign: right",
  },
  {
    identifier: "r4_3",
    primary_category: "regulatory_signs",
    secondary_category: "control_signs",
    description: "one-way roadway sign: straight",
  },
  {
    identifier: "r5",
    primary_category: "regulatory_signs",
    secondary_category: "control_signs",
    description: "pedestrian priority sign",
  },
  {
    identifier: "r101",
    primary_category: "regulatory_signs",
    secondary_category: "command_signs",
    description: "minimum speed sign",
  },
  {
    identifier: "r102",
    primary_category: "regulatory_signs",
    secondary_category: "command_signs",
    description: "vehicles exceeding mass only sign",
  },
  {
    identifier: "r103",
    primary_category: "regulatory_signs",
    secondary_category: "command_signs",
    description: "keep left only sign",
  },
  {
    identifier: "r104",
    primary_category: "regulatory_signs",
    secondary_category: "command_signs",
    description: "keep right only sign",
  },
  {
    identifier: "r105",
    primary_category: "regulatory_signs",
    secondary_category: "command_signs",
    description: "proceed left only sign",
  },
  {
    identifier: "r106",
    primary_category: "regulatory_signs",
    secondary_category: "command_signs",
    description: "proceed right only sign",
  },
  {
    identifier: "r107",
    primary_category: "regulatory_signs",
    secondary_category: "command_signs",
    description: "proceed straight only sign",
  },
  {
    identifier: "r108",
    primary_category: "regulatory_signs",
    secondary_category: "command_signs",
    description: "turn left only sign",
  },
  {
    identifier: "r109",
    primary_category: "regulatory_signs",
    secondary_category: "command_signs",
    description: "turn right only sign",
  },
  {
    identifier: "r110",
    primary_category: "regulatory_signs",
    secondary_category: "command_signs",
    description: "pedestrians only sign",
  },
  {
    identifier: "r111",
    primary_category: "regulatory_signs",
    secondary_category: "command_signs",
    description: "pedal cycles only sign",
  },
  {
    identifier: "r112",
    primary_category: "regulatory_signs",
    secondary_category: "command_signs",
    description: "pedal cycles and pedestrians only sign",
  },
  {
    identifier: "r113",
    primary_category: "regulatory_signs",
    secondary_category: "command_signs",
    description: "pedal cycles and pedestrians only sign",
  },
  {
    identifier: "r114",
    primary_category: "regulatory_signs",
    secondary_category: "command_signs",
    description: "pedestrians and pedal cycles only sign",
  },
  {
    identifier: "r115",
    primary_category: "regulatory_signs",
    secondary_category: "command_signs",
    description: "pedestrians and pedal cycles only sign",
  },
  {
    identifier: "r116",
    primary_category: "regulatory_signs",
    secondary_category: "command_signs",
    description: "motor cycles only sign",
  },
  {
    identifier: "r117",
    primary_category: "regulatory_signs",
    secondary_category: "command_signs",
    description: "motor cars only sign",
  },
  {
    identifier: "r118",
    primary_category: "regulatory_signs",
    secondary_category: "command_signs",
    description: "taxis only sign",
  },
  {
    identifier: "r119",
    primary_category: "regulatory_signs",
    secondary_category: "command_signs",
    description: "mini-buses only sign",
  },
  {
    identifier: "r120",
    primary_category: "regulatory_signs",
    secondary_category: "command_signs",
    description: "midi-buses only sign",
  },
  {
    identifier: "r121",
    primary_category: "regulatory_signs",
    secondary_category: "command_signs",
    description: "buses only sign",
  },
  {
    identifier: "r122",
    primary_category: "regulatory_signs",
    secondary_category: "command_signs",
    description: "delivery vehicles only sign",
  },
  {
    identifier: "r123",
    primary_category: "regulatory_signs",
    secondary_category: "command_signs",
    description: "goods vehicles only sign",
  },
  {
    identifier: "r124",
    primary_category: "regulatory_signs",
    secondary_category: "command_signs",
    description: "goods vehicles over indicated gross vehicle mass only sign",
  },
  {
    identifier: "r125",
    primary_category: "regulatory_signs",
    secondary_category: "command_signs",
    description: "contruction vehicles only sign",
  },
  {
    identifier: "r126",
    primary_category: "regulatory_signs",
    secondary_category: "command_signs",
    description: "vehicles conveying hazardous substances only sign",
  },
  {
    identifier: "r127",
    primary_category: "regulatory_signs",
    secondary_category: "command_signs",
    description: "abnormal vehicles only sign",
  },
  {
    identifier: "r128",
    primary_category: "regulatory_signs",
    secondary_category: "command_signs",
    description: "rickshaws only sign",
  },
  {
    identifier: "r129",
    primary_category: "regulatory_signs",
    secondary_category: "command_signs",
    description: "tour buses only sign",
  },
  {
    identifier: "r130",
    primary_category: "regulatory_signs",
    secondary_category: "command_signs",
    description: "agricultural vehicles only sign",
  },
  {
    identifier: "r131",
    primary_category: "regulatory_signs",
    secondary_category: "command_signs",
    description: "animal-drawn vehicles only sign",
  },
  {
    identifier: "r132",
    primary_category: "regulatory_signs",
    secondary_category: "command_signs",
    description: "pay toll sign",
  },
  {
    identifier: "r133",
    primary_category: "regulatory_signs",
    secondary_category: "command_signs",
    description: "switch head lamps on sign",
  },
  {
    identifier: "r134",
    primary_category: "regulatory_signs",
    secondary_category: "command_signs",
    description: "buses and mini-buses only sign",
  },
  {
    identifier: "r135",
    primary_category: "regulatory_signs",
    secondary_category: "command_signs",
    description: "buses and midi-buses only sign",
  },
  {
    identifier: "r136",
    primary_category: "regulatory_signs",
    secondary_category: "command_signs",
    description: "buses, midi-buses and mini-buses sign",
  },
];

export default signMetadata;
